service: aws-rimac-dbaes3
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "*"
      Resource: 
        - Fn::GetAtt: [UsersTable3, Arn]

        

resources:
  Resources:
    UsersTable3:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UsersTable3
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH



functions:
  api:
    handler: built/index.handler
    events:
      - httpApi:
          path: /
          method: get

  listarPeliculas:
    handler: built/application/handlers/lambda/peliculaHandler.listarPeliculas
    events:
      - httpApi:
          path: /swapi/peliculas
          method: get

  obtenerPelicula:
    handler: built/application/handlers/lambda/peliculaHandler.obtenerPelicula
    events:
      - httpApi:
          path: /swapi/peliculas/{id}
          method: get

  listarUsuarios:
    handler:  built/application/handlers/lambda/usuarioHandler.listarUsuarios
    events:
      - httpApi:
          path: /dynamo/usuarios
          method: get

  crearUsuario:
    handler: built/application/handlers/lambda/usuarioHandler.crearUsuario
    events:
      - httpApi:
          path: /dynamo/usuarios
          method: post

